language: python
sudo: false
python:
  - "2.7"
  - "3.3"
  - "3.4"
env:
  - DJANGO="Django>=1.7,<1.8" DB=sqlite
  - DJANGO="Django>=1.8,<1.9" DB=sqlite
  - DJANGO="Django>=1.9,<1.10" DB=sqlite
install:
  - pip install -U $DJANGO
  - pip install -r tests/requirements.pip
script:
  - python tests/manage.py test django_any
