language: python
python:
  - "2.7"
env:
  - DJANGO="Django==1.7" DB=mysql
  - DJANGO="Django==1.8" DB=mysql
install:
  - pip install -U $DJANGO
  - pip install -r tests/requirements.pip --use-mirrors
script:
  - python tests/manage.py test
